package com.aswin;

import java.util.Objects;

class Person {
  int id;
  int age;

  public Person(int id, int age) {
    this.id = id;
    this.age = age;
  }

  // This was generated by Intellij, under my command.
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Person person = (Person) o;
    return id == person.id &&
      age == person.age;
  }

  @Override
  public String toString() {
    return "Person{" +
      "id=" + id +
      ", age=" + age +
      '}';
  }
}

public class Main {

  public static void main(String[] args) {

    String s = new String("sss");
    String t = new String("sss");
    System.out.println("String equals :" + s.equals(t));

    Person p1 = new Person(1, 23);
    Person p2 = new Person(1, 23);
    System.out.println("Persons object equals:" + p1.equals(p2));

  }

  /*
    Equals method - Equals method plays an important role in Java.
    Equals method is in Java Object class, which incidentally is extended by All Class in java internally.
    That's why we have to use .equals() method for comparing all Objects like String, Double, Integer. (We should not use ==)
    Primitives(int, double) can be compared using == itself.
    For Classes that we write, if we want to check for equality, we have to override, equal method.

   */
}
